### ISSUE TITLE
Windows support / uploading packages?

### ISSUE THREAD

**Issue by wisehackermonkey** [kigster/arli#11]
Hello, 
I'm running on windows 10, and wanted to give you input on how it works on windows.
(note I realize that it was made for Linux)

commands that break
>arli generate PROJECT-NAME 
![image](https://user-images.githubusercontent.com/29699356/53302574-36b76200-3814-11e9-8d17-3169dc8acc6a.png)

Are you thinking about windows support at any time in the future?
Also what about allowing users to add packages to something like npm, so you dont have to host the files. users could search npm using 'arduino-*' and get back packages what have arduino libraries installed in them.

Project looks great. thanks for your time.

**Comment by kigster** [comment]
From the output you provided, it seems that the only command you are missing on windows is `sed` — I thought that the new windows BASH shell goes with most of the basic GNU tools?

If you can figure out how to install Sed on Windows, please submit a PR with additional Windows instructions in the README. I would be happy to merge it.

**Comment by wisehackermonkey** [comment]
# Here's my attempt and getting it to run by installing "sed" using chocolaty

#### Note: WSL 18.04 comes with sed but powershell doesn't 
![image](https://user-images.githubusercontent.com/29699356/120909230-d97ffd00-c627-11eb-9e3e-d169e1292b29.png)
![image](https://user-images.githubusercontent.com/29699356/120909506-9d01d080-c62a-11eb-8f61-e71ed0d9c77a.png)


## Attempt to install sed to fix issue on windows powershell

### Prerequisites: 
- chocolatey on windows [Chocolatey how to install ](https://chocolatey.org/install)
### instructions
```bash
# Open powershell as administrator
choco install ruby
# Close window & open new powershell window
refreshenv
gem install bundler
gem -v
choco install sed
```
![image](https://user-images.githubusercontent.com/29699356/120909405-9de63280-c629-11eb-8c68-59ff87036abe.png)

```
gem install arli
```
![image](https://user-images.githubusercontent.com/29699356/120909437-ebfb3600-c629-11eb-826b-836fc67328e5.png)

# Test to see if it works
```bash
arli generate test
```
![image](https://user-images.githubusercontent.com/29699356/120909470-5a3ff880-c62a-11eb-8e0a-264f56d2da69.png)

### :( don't work. 
#### says `wrong number of arguments (given 2, expected 1) (ArgumentError)`

#### also `arli` fails also 

![image](https://user-images.githubusercontent.com/29699356/120909491-822f5c00-c62a-11eb-998a-d1ac95a53547.png)


# any suggestions?

**Comment by kigster** [comment]
I'll take a look.
